### ISSUE TITLE
翻遍全网这是唯一一个我查到的使用原生GRPC搭建微服务的例子

### ISSUE THREAD

**Issue by ideallain** [WenDev/spring-boot-istio-demo#2]
其他的要么是使用哪个grpc-spring-boot-starter要么就是根本没写完，乱写一通的，这里点草demo大师。给楼主点个赞

**Comment by WenDev** [comment]
> 其他的要么是使用哪个grpc-spring-boot-starter要么就是根本没写完，乱写一通的，这里点草demo大师。给楼主点个赞

@ideallain 我也正是翻遍了全网没有找到满意的demo才自己写的，很高兴我的代码和文章能帮到你😄

**Comment by Fr3027** [comment]
我也来点个赞，太厉害了。我高中是致远中学哈哈

**Comment by WenDev** [comment]
> 我也来点个赞，太厉害了。我高中是致远中学哈哈

感谢支持😄 致远中学的话也太有缘了吧，我是山科的，可以说是对门了😆😆😆
